### ISSUE TITLE
N-37 How to use Prose

### ISSUE THREAD

**Issue by crearis** [theaterpedia/crearis-nuxt#37]
I don't understand how to use <Prose> with a content-prop or slot that serves html along with vue-components (example: Heading).

Had to build a workaround-component 'MdBlock' that allows to display html-content that get's rendered from MD on the fly.

See this in action on: 
http://localhost:3000/ausbildung-theaterpaedagogik/einstiege_complex

If we replace components/content/DataViewProduct with components/content/DataViewProductProse

we see the misbehaviour (html for 'Heading' not getting rendered)

As shown here:
![Image](https://github.com/user-attachments/assets/70bd4983-72d5-40cc-8469-5c27e53541b9)

**Comment by murisceman** [comment]
Have you tried using `v-html`?
Docs: https://vuejs.org/guide/essentials/template-syntax.html#raw-html

**Comment by crearis** [comment]
v-html is the way I have solved this. But it is no longer recomended if have understood things correctly ...
So we'll keep this issue open for a while ... to review this question later again

**Comment by murisceman** [comment]
The `v-html` directive is perfectly acceptable, except when displaying unsanitized HTML from untrusted sources, such as user inputs.

**Comment by crearis** [comment]
ahh great, so we'll stick with it!!
